name: 'Setup External Repository w/ Branch Setup'
description: 'Setup the F´ repository and tools'
inputs:
  target_repository:
    description: "External repository to checkout (<owner>/<repo>)"
    required: true
    type: string
  fprime_location:
    description: "Relative path from the external project root to its F´ submodule"
    required: false
    type: string
    default: "./lib/fprime"
  target_ref:
    description: "Branch on target repository to checkout"
    required: false
    type: string
    default: "devel"
  stage: 
    description: "Stage of the CI process"
    required: false
    default: "all"
    type: string
runs:
  using: "composite"
  steps:
    - name: "Checkout target repository"
      uses: actions/checkout@v4
      with:
        submodules: recursive 
        repository: ${{ inputs.target_repository }}
        ref: ${{ inputs.target_ref }}
        fetch-tags: true
    - name: "Overlay current F´ revision"
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: ${{ inputs.fprime_location }}
        fetch-tags: true
    - name: "Base Python"
      run: |
        pip install -U setuptools pip wheel
      shell: bash
    - name: "Install requirements.txt"
      run: |
        pip3 install -r ${{ inputs.fprime_location }}/requirements.txt
        if [ -f ./requirements.txt ]
        then
            pip3 install -r ./requirements.txt
        fi
      shell: bash
    - name: "Install CI tooling"
      run: |
        pip3 install git+https://github.com/fprime-community/fprime-ci@devel
      shell: bash
    - name: "Custom repository setup"
      if: ${{ hashFiles('./.github/actions/setup/*') != '' }}
      uses: ./.github/actions/setup
      with:
        stage: ${{ inputs.stage }}
    - name: "Version Check"
      run: |
        pip freeze
        fprime-util version-check --all-submodules
      shell: bash