name: 'Make Space: Clean-Up the Image'
description: 'A space recovery action for: Ubuntu hosts'
runs:
  using: "composite"
  steps:
  # Inspired by: https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh
  #         and: https://github.com/marketplace/actions/free-disk-space-ubuntu
  - run: |
      echo "#######################################################"
      echo "#### Making More Space                             ####"
      echo "#######################################################"
      df -h
      echo "Removing and Cleaning Large Unnecessary Packages"
      sudo apt-get remove -y '^dotnet-.*' || true
      sudo apt-get remove -y 'php.*' || true
      sudo apt-get remove -y '^mongodb-.*' || true
      sudo apt-get remove -y '^mysql-.*' || true
      sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri || true
      sudo apt-get autoremove -y || true
      sudo apt-get clean || true
    shell: bash
  - run: |
      df -h
      echo "Removing Large Unnecessary Directories"
      sudo rm -rf /usr/share/dotnet/ || true
      sudo rm -rf /usr/local/.ghcup/ || true
      sudo rm -rf /usr/local/share/powershell || true
      sudo rm -rf /usr/local/share/chromium || true
      sudo rm -rf /usr/local/lib/android || true
      sudo rm -rf /opt/ghc || true
    shell: bash
  - run: |
      df -h
      echo "Pruning Docker Images"
      sudo docker image prune --all --force || true
    shell: bash
  - run: |
      echo "#######################################################"
      echo "#### Final                                         ####"
      echo "#######################################################"
      df -h
    shell: bash
